name: iatec_authentication_firebase
description: IATec's Datasource Authentication
version: 1.0.0
publish_to: http://pub.sdasystems.org

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_facebook_auth: ^3.4.1
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.0.0
  iatec_authentication_core:
    hosted:
      name: iatec_authentication_core
      url: http://pub.sdasystems.org
    version: ^1.0.0
  flutter:
    sdk: flutter
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: