name: iatec_authentication_core
description: IATec Auth Core
version: 1.0.0
publish_to: http://pub.sdasystems.org

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  kiwi: ^3.0.0
  jwt_decoder: ^2.0.1
  dartz: ^0.9.2
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter
  pedantic: ^1.11.0

dev_dependencies:
  mockito: ^5.0.10
  flutter_test:
    sdk: flutter

flutter:
