name: adra_local_support
description: A new Flutter package project.
version: 1.0.2
publish_to: http://pub.sdasystems.org

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^2.0.1
  dartz: ^0.9.2
  google_maps_flutter: ^2.0.3
  json_serializable: ^4.1.0
  url_launcher: ^6.0.3
  location: ^4.1.1
  iatec_localization:
    hosted:
      name: iatec_localization
      url: http://pub.sdasystems.org
    version: ^0.0.12
  adra_design_system:
    hosted:
      name: adra_design_system
      url: http://pub.sdasystems.org
    version: ^0.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^2.0.1+3
  build_runner: 1.12.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
