name: adra_local_support
description: ADRA Local Supports
version: 1.0.0
publish_to: http://pub.sdasystems.org

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.2.1"

dependencies:
  json_annotation: ^4.0.1
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^2.0.1
  dartz: ^0.9.2
  google_maps_flutter: ^2.0.3
  json_serializable: ^4.1.0
  url_launcher: ^6.0.3
  location: ^4.1.1
  iatec_localization:
    hosted:
      name: iatec_localization
      url: http://pub.sdasystems.org
    version: ^1.0.0
  # adra_design_system:
  #   path: ../../Adra.Design.System
  adra_design_system:
    hosted:
      name: adra_design_system
      url: http://pub.sdasystems.org
    version: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.10
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter

flutter: