name: iatec_localization
description: Translate system
version: 1.0.0
publish_to: http://pub.sdasystems.org

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.2.1"

dependencies:
  hive_flutter: ^1.0.0
  hive: ^2.0.3
  kiwi: ^3.0.0
  connectivity: ^3.0.3
  dio: ^4.0.0
  dartz: ^0.9.2
  flutter:
    sdk: flutter
  pedantic: ^1.11.0

dev_dependencies:
  mockito: ^5.0.10
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.iatec_localization
        pluginClass: IatecLocalizationPlugin
      ios:
        pluginClass: IatecLocalizationPlugin

